create table pessoas(
id bigint not null auto_increment,
ativo bigint not null,
celular varchar(20),
cnpj varchar(20),
cpf varchar(20),
data_nascimento datetime not null,
email varchar(150),
bairro varchar(100) not null,
cep varchar(15) not null,
cidade varchar(100) not null,
complemento varchar(100),
logradouro varchar(100) not null,
numero varchar(20),
uf char(2) not null,
estado_civil varchar(50) not null,
nacionalidade varchar(50) not null,
nome varchar(200) not null,
profissao varchar(200) not null,
rg varchar(50) not null,
sexo varchar(50) not null,
telefone varchar(20),
telefone_comercial varchar(20),
tipo_pessoa varchar(20) not null,
primary key(id)
);